name: Publish to npm

on:
  push:
    tags:
      - "v*" # Trigger on tags starting with "v"

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9 # Specify the pnpm version

      # Step 3: Set up Node.js
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Set Node.js version
          cache: "pnpm" # Enable pnpm dependency caching

      # Step 4: Install dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Step 5: Run tests
      - name: Run tests
        run: pnpm test

      # Step 6: Build the project
      - name: Build the project
        run: pnpm build

      # Step 7: Publish to npm
      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # Use NPM_TOKEN for authentication
        run: pnpm publish --access public
