name: Publish to npm

on:
  push:
    tags:
      - "v*" # Triggers on tags starting with "v"

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Use your desired Node.js version
          cache: "pnpm"

      # Step 3: Install pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false # Disable automatic install as we'll run it manually later

      # Step 4: Install dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Step 5: Run tests
      - name: Run tests
        run: pnpm test

      # Step 6: Build the project
      - name: Build the project
        run: pnpm build

      # Step 7: Publish to npm
      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm publish --access public
